package org.possystem.entity;

/**
 * Record class for PriceBook entity.
 * Auto-generated by Java Record:
 * - All-args constructor
 * - Getters (upc(), name(), price(), isFeatured(), quickKeyPosition())
 * - toString()
 * - equals()
 * - hashCode()
 * Note: Records are immutable, no setters generated.
 */
public record PriceBook(
        String upc,
        String name,
        double price,
        boolean isFeatured,
        Integer quickKeyPosition
) {}