package org.possystem.entity;

import java.time.LocalDateTime;

/**
 * Record class for TransactionHeader entity.
 * Auto-generated by Java Record:
 * - All-args constructor
 * - Getters (id(), transactionDatetime(), subtotal(), discount(),
 *            tax(), total(), tenderType(), amountTendered(),
 *            changeAmount(), status())
 * - toString()
 * - equals()
 * - hashCode()
 * Note: Records are immutable, no setters generated.
 */
public record TransactionHeader(
        int id,
        LocalDateTime transactionDatetime,
        double subtotal,
        double discount,
        double tax,
        double total,
        String tenderType,
        double amountTendered,
        double changeAmount,
        String status
) {}