package org.possystem.entity;

/**
 * Record class for TransactionItem entity.
 * Auto-generated by Java Record:
 * - All-args constructor
 * - Getters (id(), transactionId(), upc(), name(),
 *            quantity(), unitPrice(), subtotal(), status())
 * - toString()
 * - equals()
 * - hashCode()
 * Note: Records are immutable, no setters generated.
 */
public record TransactionItem(
        int id,
        int transactionId,
        String upc,
        String name,
        int quantity,
        double unitPrice,
        double subtotal,
        String status
) {}